### ISSUE TITLE
你好，请问C语言版怎么设置接口nic_name

### ISSUE THREAD

**Issue by xiuqianli1996** [mchome/openwrt-dogcom#1]
用的潘多拉固件，想虚拟多个wan口给不同的接口登录不同账号尝试网速叠加，没看到设置选项

**Comment by mchome** [comment]
dogcom暂时不打算支持绑定接口。

**Comment by xiuqianli1996** [comment]
好的，谢谢

**Comment by dixyes** [comment]
bind_ip should be settable, then use uci command to find ip and genenrate config file.
so maybe it's good to change configparse.c and add "bind_ip" option.
最好能设置bind_ip，然后使用uci命令来生成配置文件
实际上直接改configparse.c加进去这个选项就行。

for now you may try my simple and bad drcom (dhcp version) implementation [dobecom](https://github.com/dixyes/dobecom) (almost deprecated)
once there be bind_ip settable, change to dogcom
至于现在可以试试我的简单而又质量很差的drcom D版c实现 [dobecom](https://github.com/dixyes/dobecom)（几近废弃）
如果dogcom支持了这个配置，换回dogcom

（自从我校不用drcom了，再也没咋写过c
（dobecom是很早以前写的，那时我连Makefile都不会写

**Comment by mchome** [comment]
就是写上ip绑定，然后让shell脚本来控制，因为还要调节iptables之类的。

**Comment by dixyes** [comment]
@mchome 那你花两分钟把bindip变成可以设置的呗

**Comment by mchome** [comment]
...
