### ISSUE TITLE
My OpenWrt router can't auto-reconnect after losing connection with this plugin.

### ISSUE THREAD

**Issue by hash070** [mchome/openwrt-dogcom#12]

**Comment by hash070** [comment]
![image](https://user-images.githubusercontent.com/62081013/102677736-a911e700-41de-11eb-82bd-ebf804a26932.png)

**Comment by hash070** [comment]
![image](https://user-images.githubusercontent.com/62081013/102677746-b333e580-41de-11eb-9ce0-9c4b66ecf341.png)

**Comment by hash070** [comment]
如果掉线了，只能重启，不能手动重连，否则出错

**Comment by d11638104** [comment]
请问你是如何编译的，你的openwrt是X86嘛？

**Comment by d11638104** [comment]
leefandy@126.com。请求你的指教

**Comment by d11638104** [comment]
> 如果掉线了，只能重启，不能手动重连，否则出错

能不能教教我如何编译

**Comment by hash070** [comment]
现在偶然看见自己提的issue，回来评论一下
首先这个插件是要在network选项里面勾选并启用的
值得注意的是这个插件仅提供命令行的操作界面，想要在OpenWrt的后台管理页面看到网页版的Dogcom需要同时编译下面这个插件
https://github.com/mchome/luci-app-dogcom
这个插件提供了dogcom 的图形化网页操作界面，在luci/app中勾选即可

**Comment by d11638104** [comment]
感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 上午10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mchome/openwrt-dogcom] 我编译好，并且装好了，但是掉线不会自动重播，咋整 (#12)





 
现在偶然看见自己提的issue，回来评论一下
 首先这个插件是要在network选项里面勾选并启用的
 值得注意的是这个插件仅提供命令行的操作界面，想要在OpenWrt的后台管理页面看到网页版的Dogcom需要同时编译下面这个插件
 https://github.com/mchome/luci-app-dogcom
 这个插件提供了dogcom 的图形化网页操作界面，在luci/app中勾选即可
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您发表了评论。消息 ID：<mchome/openwrt-dogcom/issues/12/1128327693 @ github 。com&gt;
