### ISSUE TITLE
自行编译Newifi-mini，P版，pppoe不工作

### ISSUE THREAD

**Issue by NERD-k** [mchome/openwrt-dogcom#4]
> Tue Apr  3 06:58:56 2018 daemon.notice netifd: Interface 'wan' is now down
Tue Apr  3 06:58:56 2018 daemon.notice netifd: Interface 'wan' is setting up now
Tue Apr  3 06:58:56 2018 daemon.info pppd[3508]: Plugin rp-pppoe.so loaded.
Tue Apr  3 06:58:56 2018 daemon.info pppd[3508]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.7
Tue Apr  3 06:58:56 2018 daemon.notice pppd[3508]: pppd 2.4.7 started by root, uid 0
Tue Apr  3 06:59:11 2018 daemon.warn pppd[3508]: Timeout waiting for PADO packets
Tue Apr  3 06:59:11 2018 daemon.err pppd[3508]: Unable to complete PPPoE Discovery
Tue Apr  3 06:59:11 2018 daemon.info pppd[3508]: Exit.
Tue Apr  3 06:59:11 2018 daemon.notice netifd: Interface 'wan' is now down
Tue Apr  3 06:59:11 2018 daemon.notice netifd: Interface 'wan' is setting up now
Tue Apr  3 06:59:11 2018 daemon.info pppd[3529]: Plugin rp-pppoe.so loaded.
Tue Apr  3 06:59:11 2018 daemon.info pppd[3529]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.7
Tue Apr  3 06:59:11 2018 daemon.notice pppd[3529]: pppd 2.4.7 started by root, uid 0

不明白哪里有问题，pppoe一直不工作

**Comment by mchome** [comment]
我也不知道，但至少不是dogcom的锅 :(
