### ISSUE TITLE
BUG：在一些情况下会使路由器无限重启

### ISSUE THREAD

**Issue by NERD-k** [mchome/openwrt-dogcom#5]
本人使用 **Newifi mini**，官方原版 **LEDE-17.01.4**，按照GitHub上的教程自行编译的 openwrt-dogcom。
#### BUG出现
如果路由器断电重启，即dogcom开机自运行，使得路由器通过pppoe进入网络后一段时间内，出现无限重启的现象。
#### 临时解决方法
开机后关闭dogcom，再打开dogcom连入网络。

**Comment by NERD-k** [comment]
**有兴趣**深入了解的自行研究，Emmm，我短期内应该没时间研究，由于我是使用官方的固件自行安装的服务、程序等，也可能与其他的程序包有关，但由上述的*临时解决方法*能确认和dogcom一定有关。

贴上异常的系统日志，内核警告 `kernel.log`
> Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.744950] ------------[ cut here ]------------
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.749707] WARNING: CPU: 0 PID: 2888 at net/core/skbuff.c:4196 0x801f1fc4()
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.756953] Modules linked in: ifb iptable_nat usb_serial_simple rt2800soc rt2800pci rt2800mmio rt2800lib pppoe nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_socket xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TPROXY xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_DSCP xt_CT xt_Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.909918] CPU: 0 PID: 2888 Comm: sh Not tainted 4.4.92 #0
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.915614] Stack : 8031587c 00000000 00000001 80360000 00000000 00000000 00000000 00000000
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.915614] 	  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.915614] 	  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.915614] 	  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.915614] 	  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.915614] 	  ...
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.951994] Call Trace:[<800144e0>] 0x800144e0
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.956578] [<800144e0>] 0x800144e0
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.960135] [<80025054>] 0x80025054
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.963709] [<801f1fc4>] 0x801f1fc4
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.967302] [<8002510c>] 0x8002510c
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.970873] [<801f1fc4>] 0x801f1fc4
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.974504] [<8024ba34>] 0x8024ba34
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.978096] [<86d307f4>] 0x86d307f4 [nf_conntrack@86d30000+0xc840]
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.984434] [<8024c018>] 0x8024c018
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.988013] [<86d2d97c>] 0x86d2d97c [nf_nat@86d2c000+0x2620]
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.993823] [<80250828>] 0x80250828
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   79.997407] [<86d24448>] 0x86d24448 [ip_tables@86d24000+0x2410]
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.003506] [<802584e8>] 0x802584e8
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.007104] [<8025ad34>] 0x8025ad34
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.010736] [<80231e98>] 0x80231e98
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.014333] [<802383b8>] 0x802383b8
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.017935] [<80238970>] 0x80238970
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.021524] [<80080002>] 0x80080002
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.025094] [<8023825c>] 0x8023825c
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.028676] [<80238c3c>] 0x80238c3c
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.032248] [<800a5064>] 0x800a5064
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.035867] [<80238480>] 0x80238480
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.039447] [<80200f54>] 0x80200f54
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.043064] [<877a632c>] 0x877a632c [mt76@877a4000+0x3c60]
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.048669] [<801f4304>] 0x801f4304
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.052240] [<800a51c0>] 0x800a51c0
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.055849] [<802de41c>] 0x802de41c
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.059429] [<801f2cc8>] 0x801f2cc8
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.063013] [<800ba530>] 0x800ba530
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.066635] [<802de95c>] 0x802de95c
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.070216] [<801f4ab8>] 0x801f4ab8
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.073830] [<802ded5c>] 0x802ded5c
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.077387] [<8025f710>] 0x8025f710
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.080984] [<8025fa88>] 0x8025fa88
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.084565] [<8026f3f0>] 0x8026f3f0
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.088145] [<802de9e0>] 0x802de9e0
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.091715] [<80200cd0>] 0x80200cd0
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.095297] [<80202360>] 0x80202360
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.098929] [<802024ec>] 0x802024ec
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.102544] [<86ca0704>] 0x86ca0704 [mac80211@86c80000+0x5ff80]
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.108656] [<86ca3580>] 0x86ca3580 [mac80211@86c80000+0x5ff80]
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.114830] [<86ca5780>] 0x86ca5780 [mac80211@86c80000+0x5ff80]
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.120879] [<86cd2dac>] 0x86cd2dac [mac80211@86c80000+0x5ff80]
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.126975] [<877b0c34>] 0x877b0c34 [mt76x2e@877b0000+0x9680]
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.132976] [<86ca5f84>] 0x86ca5f84 [mac80211@86c80000+0x5ff80]
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.139182] [<877a598c>] 0x877a598c [mt76@877a4000+0x3c60]
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.144879] [<877a50e8>] 0x877a50e8 [mt76@877a4000+0x3c60]
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.150548] [<80201ef0>] 0x80201ef0
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.154178] [<800275d4>] 0x800275d4
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.157759] [<8004f2fc>] 0x8004f2fc
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.161336] [<8004b7fc>] 0x8004b7fc
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.164967] [<800047f8>] 0x800047f8
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.168532] 
Wed Apr 18 17:13:22 2018 kern.warn kernel: [   80.170052] ---[ end trace 975d224c1f9892eb ]---

**Comment by mchome** [comment]
只有那段没人看得懂的kernel.log
![image](https://user-images.githubusercontent.com/7392658/38926491-75954dcc-4335-11e8-9d57-646e9d5d13e3.png)
如果"临时解决方法"能用，我觉得是不是你改系统改错了什么？

**Comment by NERD-k** [comment]
使用*临时解决方法*后， `kernel.log`里便不会出现上述的内核警告信息，我也是刚搞好才发现的，具体问题我也不是很清楚了
