### ISSUE TITLE
架构不兼容

### ISSUE THREAD

**Issue by lysssssss** [mchome/openwrt-dogcom#8]
root@OpenWrt:~# opkg install /usr/dogcom_v1.6.2-1_mipsel_24kc.ipk 
Unknown package 'dogcom'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for dogcom found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package dogcom.

路由器斐讯k2p ，CPU为MTK7621，查了很多资料说7621是1004kc，是这样吗，请问又应该在哪里改呢，是在sdk里吗？

**Comment by mchome** [comment]
我没发过安装包，自己替换sdk重新编译。

**Comment by lysssssss** [comment]
> 我没发过安装包，自己替换sdk重新编译。

这个是我自己编译的，编译出来是24kc，无法安装。

**Comment by mchome** [comment]
k2p的话，[这里](https://www.right.com.cn/forum/thread-215978-1-1.html)应该很详细了。
